<?php
class SS_Loader extends CI_Loader{
	
	var $main_view_loaded=FALSE;
	var $sidebar_loaded=FALSE;

	var $require_head=true;//页面头尾输出开关（含menu）
	var $require_menu=true;//顶部蓝条/菜单输出开关
	var $view_data=array();//要传递给视图的参数
	
	var $sidebar_data='';
	
	/**
	 * 在ajax响应页面中，用来保存提示信息的数组
	 */
	var $message=array(
		'notice'=>array(),
		'warning'=>array()
	);
	
	function __construct(){
		parent::__construct();
	}

	function getViewData($param=NULL){
		if(isset($param)){
			return $this->view_data[$param];
		}else{
			return $this->view_data;
		}
	}
	
	/**
	 * 将数据传输给视图
	 * @param $name 视图中可以调用的变量名
	 * @param $value 数据
	 */
	function addViewData($name,$value){
		$this->view_data+=array($name=>$value);
	}
	
	/**
	 * 将数据传输给视图（数组形式）
	 * @param array $array 数据 Array(视图中可以调用的变量名=>值,..)
	 */
	function addViewArrayData(array $array){
		$this->view_data+=$array;
	}
	
	function message($message,$type='notice'){
		$this->message[$type][]=$message;
	}
	
	/**
	 * @param $return: FALSE:进入输出缓存,TRUE:作为字符串返回,'sidebar':加入边栏
	 */
	function view($view, array $vars = array(), $return = FALSE){
		
		$vars=array_merge($vars,$this->getViewData());//每次载入视图时，都将当前视图数据传递给他一次
		
		if($return === 'sidebar'){
			$this->sidebar_data.=parent::view($view, $vars, TRUE);
		}else{
			return parent::view($view, $vars, $return);
		}
	}
	
	function value($index){
		if(!is_null(post($index))){
			return post($index);
		}else{
			$CI=&get_instance();

			$view_data=$CI->load->view_data;

			$index_array=explode('/',$index);

			if(isset($view_data[$index_array[0]])){
				$value=$view_data[$index_array[0]];
			}else{
				return;
			}

			for($i=1;$i<count($index_array);$i++){
				if(isset($value[$index_array[$i]])){
					$value=$value[$index_array[$i]];
				}else{
					return;
				}
			}

			return $value;
		}
	}

	function arrayExportExcel(array $array){
		//TODO arrayExportExcel
		require APPPATH.'third_party/PHPExcel/PHPExcel.php';
		require APPPATH.'third_party/PHPExcel/PHPExcel/Writer/Excel5.php';

		$objExcel = new PHPExcel();
		$objWriter = new PHPExcel_Writer_Excel5($objExcel);
		$objProps = $objExcel->getProperties();
		$objProps->setCreator($_SESSION['username']);
		$objProps->setLastModifiedBy($_SESSION['username']);
		/*$objProps->setTitle($file_title);
		$objProps->setSubject("Office XLS Test Document, Demo"); 
		$objProps->setDescription("Test document, generated by PHPExcel.");
		$objProps->setKeywords("office excel PHPExcel");
		$objProps->setCategory("Test");*/

		$objExcel->setActiveSheetIndex(0); 
		$objActSheet = $objExcel->getActiveSheet();  

		//设置当前活动sheet的名称  
		$objActSheet->setTitle('sheet1');  

		//设置单元格内容  由PHPExcel根据传入内容自动判断单元格内容类型  
		$objActSheet->setCellValue('A1', '字符串内容');  // 字符串内容  
		$objActSheet->setCellValue('A2', 26);            // 数值  
		$objActSheet->setCellValue('A3', true);          // 布尔值  
		$objActSheet->setCellValue('A4', '=SUM(A2:A2)'); // 公式   

		$fields=$array['_field'];unset($array['_field']);

		foreach($fields as $field_name=>$value){
			echo '<td field="'.$field_name.'"'.(is_array($value) && isset($value['attrib'])?' '.$value['attrib']:'').'>'.(is_array($value)?$value['html']:$value).'</td>';
		}

		foreach($array as $linearray){
			foreach($fields as $field_name=>$value){
				$html=is_array($linearray[$field_name])?$linearray[$field_name]['html']:$linearray[$field_name];
				echo '<td field="'.$field_name.'"'.(is_array($linearray[$field_name]) && isset($linearray[$field_name]['attrib'])?' '.$linearray[$field_name]['attrib']:'').'>'.$html.'</td>';
			}

		}
		$objWriter->save('php://output');
	}

}
?>