<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/*
| -------------------------------------------------------------------
| MIME TYPES
| -------------------------------------------------------------------
| This file contains an array of mime types.  It is used by the
| Upload class to help identify allowed file types.
|
*/

$mimes = array (
				'001' => 'application/x-001',
				'301' => 'application/x-301',
				'323' => 'text/h323',
				'906' => 'application/x-906',
				'907' => 'drawing/907',
				'a11' => 'application/x-a11',
				'acp' => 'audio/x-mei-aac',
				'ai' => 'application/postscript',
				'aif' => 'audio/x-aiff',
				'aifc' => 'audio/x-aiff',
				'aiff' => 'audio/x-aiff',
				'anv' => 'application/x-anv',
				'asa' => 'text/asa',
				'asf' => 'video/x-ms-asf',
				'asp' => 'text/asp',
				'asx' => 'video/x-ms-asf',
				'au' => 'audio/basic',
				'avi' => 'video/x-msvideo',
				'awf' => 'application/vnd.adobe.workflow',
				'bcpio' => 'application/x-bcpio',
				'bin' => 'application/macbinary',
				'biz' => 'text/xml',
				'bmp' => array (
					'image/bmp',
					'image/x-windows-bmp',
				),
				'bot' => 'application/x-bot',
				'c' => 'text/plain',
				'c4t' => 'application/x-c4t',
				'c90' => 'application/x-c90',
				'cal' => 'application/x-cals',
				'cat' => 'application/vnd.ms-pki.seccat',
				'cc' => 'text/plain',
				'cdf' => 'application/x-netcdf',
				'cdr' => 'application/x-cdr',
				'cel' => 'application/x-cel',
				'cer' => 'application/x-x509-ca-cert',
				'cg4' => 'application/x-g4',
				'cgm' => 'application/x-cgm',
				'chm' => 'application/octet-stream',
				'cit' => 'application/x-cit',
				'class' => 'application/octet-stream',
				'cml' => 'text/xml',
				'cmp' => 'application/x-cmp',
				'cmx' => 'application/x-cmx',
				'cot' => 'application/x-cot',
				'cpio' => 'application/x-cpio',
				'cpt' => 'application/mac-compactpro',
				'crl' => 'application/pkix-crl',
				'crt' => 'application/x-x509-ca-cert',
				'csh' => 'application/x-csh',
				'csi' => 'application/x-csi',
				'css' => 'text/css',
				'csv' => array (
					'text/x-comma-separated-values',
					'text/comma-separated-values',
					'application/octet-stream',
					'application/vnd.ms-excel',
					'application/x-csv',
					'text/x-csv',
					'text/csv',
					'application/csv',
					'application/excel',
					'application/vnd.msexcel',
				),
				'cut' => 'application/x-cut',
				'dbf' => 'application/x-dbf',
				'dbm' => 'application/x-dbm',
				'dbx' => 'application/x-dbx',
				'dcd' => 'text/xml',
				'dcr' => 'application/x-director',
				'dcx' => 'application/x-dcx',
				'der' => 'application/x-x509-ca-cert',
				'dgn' => 'application/x-dgn',
				'dib' => 'application/x-dib',
				'dir' => 'application/x-director',
				'dll' => 'application/octet-stream',
				'dms' => 'application/octet-stream',
				'doc' => 'application/msword',
				'docx' => array (
					'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
					'application/zip',
				),
				'dot' => 'application/msword',
				'dotx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
				'drw' => 'application/x-drw',
				'dtd' => 'text/xml',
				'dvi' => 'application/x-dvi',
				'dwf' => 'application/x-dwf',
				'dwg' => 'application/x-dwg',
				'dxb' => 'application/x-dxb',
				'dxf' => 'application/x-dxf',
				'dxr' => 'application/x-director',
				'edn' => 'application/vnd.adobe.edn',
				'emf' => 'application/x-emf',
				'eml' => 'message/rfc822',
				'ent' => 'text/xml',
				'epi' => 'application/x-epi',
				'eps' => 'application/postscript',
				'es' => 'application/postsrcipt',
				'etd' => 'application/x-ebx',
				'etx' => 'text/x-setext',
				'exe' => array (
					'application/octet-stream',
					'application/x-msdownload',
				),
				'fax' => 'image/fax',
				'fdf' => 'application/vnd.fdf',
				'fif' => 'application/fractals',
				'fo' => 'text/xml',
				'frm' => 'application/x-frm',
				'g4' => 'application/x-g4',
				'gbr' => 'application/x-gbr',
				'gcd' => 'application/x-gcd',
				'gif' => 'image/gif',
				'gl2' => 'application/x-gl2',
				'gp4' => 'application/x-gp4',
				'gtar' => 'application/x-gtar',
				'gz' => 'application/x-gzip',
				'h' => 'text/plain',
				'hdf' => 'application/x-hdf',
				'hgl' => 'application/x-hgl',
				'hmr' => 'application/x-hmr',
				'hpg' => 'application/x-hpgl',
				'hpl' => 'application/x-hpl',
				'hqx' => 'application/mac-binhex40',
				'hrf' => 'application/x-hrf',
				'hta' => 'application/hta',
				'htc' => 'text/x-component',
				'htl' => 'text/html',
				'htm' => 'text/html',
				'html' => 'text/html',
				'htt' => 'text/webviewhtml',
				'htx' => 'text/html',
				'icb' => 'application/x-icb',
				'ico' => 'application/x-ico',
				'ief' => 'image/ief',
				'iff' => 'application/x-iff',
				'ig4' => 'application/x-g4',
				'igs' => 'application/x-igs',
				'iii' => 'application/x-iphone',
				'img' => 'application/x-img',
				'ins' => 'application/x-internet-signup',
				'isp' => 'application/x-internet-signup',
				'ivf' => 'video/x-ivf',
				'java' => 'java/*',
				'jfif' => 'image/jpeg',
				'jpe' => array (
					'image/jpeg',
					'image/pjpeg',
				),
				'jpeg' => array (
					'image/jpeg',
					'image/pjpeg',
				),
				'jpg' => array (
					'image/jpeg',
					'image/pjpeg',
				),
				'js' => 'application/x-javascript',
				'json' => array (
					'application/json',
					'text/json',
				),
				'jsp' => 'text/html',
				'la1' => 'audio/x-liquid-file',
				'lar' => 'application/x-laplayer-reg',
				'latex' => 'application/x-latex',
				'lavs' => 'audio/x-liquid-secure',
				'lbm' => 'application/x-lbm',
				'lha' => 'application/octet-stream',
				'lmsff' => 'audio/x-la-lms',
				'log' => array (
					'text/plain',
					'text/x-log',
				),
				'ls' => 'application/x-javascript',
				'ltr' => 'application/x-ltr',
				'lzh' => 'application/octet-stream',
				'm1v' => 'video/x-mpeg',
				'm2v' => 'video/x-mpeg',
				'm3u' => 'audio/mpegurl',
				'm4e' => 'video/mpeg4',
				'mac' => 'application/x-mac',
				'man' => 'application/x-troff-man',
				'math' => 'text/xml',
				'mdb' => 'application/x-mdb',
				'me' => 'application/x-troll-me',
				'mfp' => 'application/x-shockwave-flash',
				'mht' => 'message/rfc822',
				'mhtml' => 'message/rfc822',
				'mi' => 'application/x-mi',
				'mid' => 'audio/midi',
				'midi' => 'audio/midi',
				'mif' => 'application/vnd.mif',
				'mil' => 'application/x-mil',
				'mml' => 'text/xml',
				'mnd' => 'audio/x-musicnet-download',
				'mns' => 'audio/x-musicnet-stream',
				'mocha' => 'application/x-javascript',
				'moov' => 'video/quicktime',
				'mov' => 'video/quicktime',
				'movie' => 'video/x-sgi-movie',
				'mp1' => 'audio/mp1',
				'mp2' => 'audio/mpeg',
				'mp2v' => 'video/mpeg',
				'mp3' => array (
					'audio/mpeg',
					'audio/mpg',
					'audio/mpeg3',
					'audio/mp3',
				),
				'mp4' => 'video/mpeg4',
				'mpa' => 'video/x-mpg',
				'mpd' => 'application/vnd.ms-project',
				'mpe' => 'video/mpeg',
				'mpeg' => 'video/mpeg',
				'mpg' => 'video/mpeg',
				'mpga' => 'audio/mpeg',
				'mpp' => 'application/vnd.ms-project',
				'mps' => 'video/x-mpeg',
				'mpt' => 'application/vnd.ms-project',
				'mpv' => 'video/mpg',
				'mpv2' => 'video/mpeg',
				'mpw' => 'application/vnd.ms-project',
				'mpx' => 'application/vnd.ms-project',
				'mtx' => 'text/xml',
				'mxp' => 'application/x-mmxp',
				'myz' => 'application/myz',
				'nc' => 'application/x-netcdf',
				'net' => 'image/pnetvue',
				'nrf' => 'application/x-nrf',
				'nws' => 'message/rfc822',
				'oda' => 'application/oda',
				'odc' => 'text/x-ms-odc',
				'out' => 'application/x-out',
				'p10' => 'application/pkcs10',
				'p12' => 'application/x-pkcs12',
				'p7b' => 'application/x-pkcs7-certificates',
				'p7c' => 'application/pkcs7-mime',
				'p7m' => 'application/pkcs7-mime',
				'p7r' => 'application/x-pkcs7-certreqresp',
				'p7s' => 'application/pkcs7-signature',
				'pbm' => 'image/x-portable-bitmap',
				'pc5' => 'application/x-pc5',
				'pci' => 'application/x-pci',
				'pcl' => 'application/x-pcl',
				'pcx' => 'application/x-pcx',
				'pdf' => array (
					'application/pdf',
					'application/x-download',
				),
				'pdx' => 'application/vnd.adobe.pdx',
				'pfx' => 'application/x-pkcs12',
				'pgl' => 'application/x-pgl',
				'pgm' => 'image/x-portable-graymap',
				'php' => 'application/x-httpd-php',
				'php3' => 'application/x-httpd-php',
				'php4' => 'application/x-httpd-php',
				'phps' => 'application/x-httpd-php-source',
				'phtml' => 'application/x-httpd-php',
				'pic' => 'application/x-pic',
				'pko' => 'application/vnd.ms-pki.pko',
				'pl' => 'application/x-perl',
				'plg' => 'text/html',
				'pls' => 'audio/scpls',
				'plt' => 'application/x-plt',
				'png' => array (
					'image/png',
					'image/x-png',
				),
				'pnm' => 'image/x-portable-anymap',
				'pot' => 'application/vnd.ms-powerpoint',
				'potx' => 'application/vnd.openxmlformats-officedocument.presentationml.template',
				'ppa' => 'application/vnd.ms-powerpoint',
				'ppm' => 'application/x-ppm',
				'pps' => 'application/vnd.ms-powerpoint',
				'ppsx' => 'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
				'ppt' => 
				array (
					'application/powerpoint',
					'application/vnd.ms-powerpoint',
				),
				'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
				'pr' => 'application/x-pr',
				'prf' => 'application/pics-rules',
				'prn' => 'application/x-prn',
				'prt' => 'application/x-prt',
				'ps' => 'application/postscript',
				'psd' => 'application/x-photoshop',
				'ptn' => 'application/x-ptn',
				'pwz' => 'application/vnd.ms-powerpoint',
				'qt' => 'video/quicktime',
				'r3t' => 'text/vnd.rn-realtext3d',
				'ra' => 'audio/x-realaudio',
				'ram' => 'audio/x-pn-realaudio',
				'rar' => 'application/octet-stream',
				'ras' => 'application/x-ras',
				'rat' => 'application/rat-file',
				'rdf' => 'text/xml',
				'rec' => 'application/vnd.rn-recording',
				'red' => 'application/x-red',
				'rgb' => 'application/x-rgb',
				'rjs' => 'application/vnd.rn-realsystem-rjs',
				'rjt' => 'application/vnd.rn-realsystem-rjt',
				'rlc' => 'application/x-rlc',
				'rle' => 'application/x-rle',
				'rm' => 'audio/x-pn-realaudio',
				'rmf' => 'application/vnd.adobe.rmf',
				'rmi' => 'audio/mid',
				'rmj' => 'application/vnd.rn-realsystem-rmj',
				'rmm' => 'audio/x-pn-realaudio',
				'rmp' => 'application/vnd.rn-rn_music_package',
				'rms' => 'application/vnd.rn-realmedia-secure',
				'rmvb' => 'application/vnd.rn-realmedia-vbr',
				'rmx' => 'application/vnd.rn-realsystem-rmx',
				'rnx' => 'application/vnd.rn-realplayer',
				'roff' => 'application/x-troff',
				'rp' => 'image/vnd.rn-realpix',
				'rpm' => 'audio/x-pn-realaudio-plugin',
				'rsml' => 'application/vnd.rn-rsml',
				'rt' => 'text/vnd.rn-realtext',
				'rtf' => 'text/rtf',
				'rtx' => 'text/richtext',
				'rv' => 'video/vnd.rn-realvideo',
				'sam' => 'application/x-sam',
				'sat' => 'application/x-sat',
				'sdp' => 'application/sdp',
				'sdw' => 'application/x-sdw',
				'sea' => 'application/octet-stream',
				'sh' => 'application/x-sh',
				'shar' => 'application/x-shar',
				'shtml' => 'text/html',
				'sit' => 'application/x-stuffit',
				'slb' => 'application/x-slb',
				'sld' => 'application/x-sld',
				'sldx' => 'application/vnd.openxmlformats-officedocument.presentationml.slide',
				'slk' => 'drawing/x-slk',
				'smi' => 'application/smil',
				'smil' => 'application/smil',
				'smk' => 'application/x-smk',
				'snd' => 'audio/basic',
				'so' => 'application/octet-stream',
				'sol' => 'text/plain',
				'sor' => 'text/plain',
				'spc' => 'application/x-pkcs7-certificates',
				'spl' => 'application/futuresplash',
				'spp' => 'text/xml',
				'src' => 'application/x-wais-source',
				'ssm' => 'application/streamingmedia',
				'sst' => 'application/vnd.ms-pki.certstore',
				'stl' => 'application/vnd.ms-pki.stl',
				'stm' => 'text/html',
				'sty' => 'application/x-sty',
				'sv4cpio' => 'application/x-sv4cpio',
				'sv4crc' => 'application/x-sv4crc',
				'svg' => 'text/xml',
				'swf' => 'application/x-shockwave-flash',
				't' => 'application/x-troff',
				'tar' => 'application/x-tar',
				'tcl' => 'application/x-tcl',
				'tdf' => 'application/x-tdf',
				'tex' => 'application/x-tex',
				'texi' => 'application/x-texinfo',
				'texinfo' => 'application/x-texinfo',
				'text' => 'text/plain',
				'tg4' => 'application/x-tg4',
				'tga' => 'application/x-tga',
				'tgz' => array (
					'application/x-tar',
					'application/x-gzip-compressed',
				),
				'tif' => 'image/tiff',
				'tiff' => 'image/tiff',
				'tld' => 'text/xml',
				'top' => 'drawing/x-top',
				'torrent' => 'application/x-bittorrent',
				'tr' => 'application/x-troff',
				'ts' => 'application/x-troll-ts',
				'tsd' => 'text/xml',
				'tsv' => 'text/tab-separated-values',
				'txt' => 'text/plain',
				'uin' => 'application/x-icq',
				'uls' => 'text/iuls',
				'ustar' => 'application/x-ustar',
				'vcf' => 'text/x-vcard',
				'vda' => 'application/x-vda',
				'vdx' => 'application/vnd.visio',
				'vml' => 'text/xml',
				'vpg' => 'application/x-vpeg005',
				'vsd' => 'application/x-vsd',
				'vss' => 'application/vnd.visio',
				'vst' => 'application/x-vst',
				'vsw' => 'application/vnd.visio',
				'vsx' => 'application/vnd.visio',
				'vtx' => 'application/vnd.visio',
				'vxml' => 'text/xml',
				'wav' => array (
					'audio/x-wav',
					'audio/wave',
					'audio/wav',
				),
				'wax' => 'audio/x-ms-wax',
				'wb1' => 'application/x-wb1',
				'wb2' => 'application/x-wb2',
				'wb3' => 'application/x-wb3',
				'wbmp' => 'image/vnd.wap.wbmp',
				'wbxml' => 'application/wbxml',
				'wiz' => 'application/msword',
				'wk3' => 'application/x-wk3',
				'wk4' => 'application/x-wk4',
				'wkq' => 'application/x-wkq',
				'wks' => 'application/x-wks',
				'wm' => 'video/x-ms-wm',
				'wma' => 'audio/x-ms-wma',
				'wmd' => 'application/x-ms-wmd',
				'wmf' => 'application/x-wmf',
				'wml' => 'text/vnd.wap.wml',
				'wmlc' => 'application/wmlc',
				'wmv' => 'video/x-ms-wmv',
				'wmx' => 'video/x-ms-wmx',
				'wmz' => 'application/x-ms-wmz',
				'word' => array (
					'application/msword',
					'application/octet-stream',
				),
				'wp6' => 'application/x-wp6',
				'wpd' => 'application/x-wpd',
				'wpg' => 'application/x-wpg',
				'wpl' => 'application/vnd.ms-wpl',
				'wq1' => 'application/x-wq1',
				'wr1' => 'application/x-wr1',
				'wri' => 'application/x-wri',
				'wrk' => 'application/x-wrk',
				'ws' => 'application/x-ws',
				'ws2' => 'application/x-ws',
				'wsc' => 'text/scriptlet',
				'wsdl' => 'text/xml',
				'wvx' => 'video/x-ms-wvx',
				'x_b' => 'application/x-x_b',
				'x_t' => 'application/x-x_t',
				'xbm' => 'image/x-xbitmap',
				'xdp' => 'application/vnd.adobe.xdp',
				'xdr' => 'text/xml',
				'xfd' => 'application/vnd.adobe.xfd',
				'xfdf' => 'application/vnd.adobe.xfdf',
				'xht' => 'application/xhtml+xml',
				'xhtml' => 'application/xhtml+xml',
				'xl' => 'application/excel',
				'xlam' => 'application/vnd.ms-excel.addin.macroEnabled.12',
				'xls' => array (
					'application/excel',
					'application/vnd.ms-excel',
					'application/msexcel',
				),
				'xlsb' => 'application/vnd.ms-excel.sheet.binary.macroEnabled.12',
				'xlsx' => array (
					'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
					'application/zip',
				),
				'xltx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
				'xlw' => 'application/x-xlw',
				'xml' => 'text/xml',
				'xpl' => 'audio/scpls',
				'xpm' => 'image/x-xpixmap',
				'xq' => 'text/xml',
				'xql' => 'text/xml',
				'xquery' => 'text/xml',
				'xsd' => 'text/xml',
				'xsl' => 'text/xml',
				'xslt' => 'text/xml',
				'xwd' => 'application/x-xwd',
				'zip' => array (
					'application/x-zip',
					'application/zip',
					'application/x-zip-compressed',
				),
);


/* End of file mimes.php */
/* Location: ./application/config/mimes.php */
